services:
  - type: web
    name: harmony-erp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn harmony_erp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: harmony_erp.settings
      - key: PYTHON_VERSION
        value: 3.10
